name: Amul Stock Monitor
on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'  # Fixed: Added missing * * *
  workflow_dispatch: # Allow manual trigger
  
permissions:
  contents: write
  
jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run stock monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python amulStockAlert.py
        echo "Python script completed"
        echo "Files created:"
        ls -la stock_* 2>/dev/null || echo "No stock files found"
      
    - name: Commit and push state file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check what files exist
        echo "Checking for files to commit:"
        ls -la stock_* 2>/dev/null || echo "No stock files found"
        
        # Add files if they exist
        git add stock_state.json 2>/dev/null || echo "stock_state.json not found"
        git add stock_monitor.log 2>/dev/null || echo "stock_monitor.log not found"
        
        # Check for staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Update stock monitoring state [skip ci]"
          git push
        fi
