name: Amul Stock Monitor
on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger
  
permissions:
  contents: write
  
jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        # Install other dependencies if requirements.txt exists
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        
    - name: Run stock monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        echo "Starting stock monitor..."
        python amulStockAlert.py
        echo "Stock monitor completed"
        
    - name: Check created files
      run: |
        echo "=== Current directory contents ==="
        ls -la
        echo "=== Looking for stock files ==="
        find . -name "stock_*" -type f -exec ls -la {} \; || echo "No stock files found"
        echo "=== File contents (if they exist) ==="
        if [ -f "stock_state.json" ]; then
          echo "stock_state.json exists:"
          cat stock_state.json
        else
          echo "stock_state.json does not exist"
        fi
        if [ -f "stock_monitor.log" ]; then
          echo "stock_monitor.log exists (last 10 lines):"
          tail -10 stock_monitor.log
        else
          echo "stock_monitor.log does not exist"
        fi
      
    - name: Commit and push state file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check git status
        echo "=== Git status before adding files ==="
        git status
        
        # Add files that exist
        files_to_add=""
        if [ -f "stock_state.json" ]; then
          git add stock_state.json
          files_to_add="$files_to_add stock_state.json"
        fi
        if [ -f "stock_monitor.log" ]; then
          git add stock_monitor.log  
          files_to_add="$files_to_add stock_monitor.log"
        fi
        
        echo "=== Git status after adding files ==="
        git status
        
        # Check for staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes for files: $files_to_add"
          git commit -m "Update stock monitoring state [skip ci]"
          echo "Pushing changes..."
          git push
          echo "Push completed"
        fi
